services:
  rendering-service:
    build:
      context: .
      dockerfile: apps/rendering-service/Dockerfile
    image: rendering-service:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: luminth-redis
