"""Set up cascade delete for canvas

Revision ID: 40112bba580e
Revises: 7b75ae65d0f4
Create Date: 2025-07-01 09:24:28.517918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40112bba580e'
down_revision: Union[str, Sequence[str], None] = '7b75ae65d0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canvas', 'latest_render_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('canvas_author_id_fkey'), 'canvas', type_='foreignkey')
    op.create_foreign_key(None, 'canvas', 'user', ['author_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('prompt', 'latest_render_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt', 'latest_render_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'canvas', type_='foreignkey')
    op.create_foreign_key(op.f('canvas_author_id_fkey'), 'canvas', 'user', ['author_id'], ['user_id'])
    op.alter_column('canvas', 'latest_render_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
