"""Fixed race conditions in update

Revision ID: 7b75ae65d0f4
Revises: e30e467a647d
Create Date: 2025-06-29 09:38:52.686333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b75ae65d0f4'
down_revision: Union[str, Sequence[str], None] = 'e30e467a647d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canvas', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('canvas', sa.Column('latest_render_at', sa.DateTime(), nullable=True))
    op.drop_column('canvas', 'created_at')
    op.add_column('prompt', sa.Column('latest_render_at', sa.DateTime(), nullable=True))
    op.drop_column('prompt', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('prompt', 'latest_render_at')
    op.add_column('canvas', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('canvas', 'latest_render_at')
    op.drop_column('canvas', 'title')
    # ### end Alembic commands ###
