"""Gave avatar a default value in User table

Revision ID: 922de12fa7d1
Revises: ab74aab9eceb
Create Date: 2025-07-10 15:25:24.715604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '922de12fa7d1'
down_revision: Union[str, Sequence[str], None] = 'ab74aab9eceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
