"""Initialised db

Revision ID: ea0738ca4d16
Revises: 
Create Date: 2025-07-01 16:16:17.768087

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea0738ca4d16'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_daily_limit', sa.Integer(), nullable=False),
    sa.Column('render_daily_limit', sa.Integer(), nullable=False),
    sa.Column('prompt_requests_today', sa.Integer(), nullable=False),
    sa.Column('render_requests_today', sa.Integer(), nullable=False),
    sa.Column('last_request_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('canvas',
    sa.Column('canvas_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('latest_render_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('canvas_id')
    )
    op.create_index(op.f('ix_canvas_author_id'), 'canvas', ['author_id'], unique=False)
    op.create_index(op.f('ix_canvas_canvas_id'), 'canvas', ['canvas_id'], unique=False)
    op.create_table('prompt',
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('latest_render_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index(op.f('ix_prompt_author_id'), 'prompt', ['author_id'], unique=False)
    op.create_index(op.f('ix_prompt_prompt_id'), 'prompt', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_prompt_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_author_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_canvas_canvas_id'), table_name='canvas')
    op.drop_index(op.f('ix_canvas_author_id'), table_name='canvas')
    op.drop_table('canvas')
    op.drop_table('user')
    # ### end Alembic commands ###
