# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# permissions:
#   actions: read
#   contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           filter: tree:0
#           fetch-depth: 0

#       # This enables task distribution via Nx Cloud
#       # Run this command as early as possible, before dependencies are installed
#       # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
#       # Uncomment this line to enable task distribution
#       # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

#       # Cache node_modules
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'yarn'

#       - uses: actions/checkout@v4

#       - run: yarn install --frozen-lockfile

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#             python-version: '3.11'

#       - name: Install system dependencies for manimpango
#         run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev libcairo2-dev pkg-config python3-dev

#       - name: Install uv
#         uses: astral-sh/setup-uv@v5

#       - name: Cache uv cache
#         uses: actions/cache@v4
#         with:
#           path: ~/.cache/uv
#           key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-uv-

#       - name: Install dependencies for db-core library
#         working-directory: libs/db-core
#         run: uv sync

#       - name: Install dependencies for rendering-service
#         working-directory: apps/rendering-service
#         run: uv sync

#       - name: Install dependencies for user-service
#         working-directory: apps/user-service
#         run: uv sync

#       - uses: nrwl/nx-set-shas@v4

#       # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
#       # - run: npx nx-cloud record -- echo Hello World
#       # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
#       - run: npx nx affected -t build
#       # - run: npx nx affected -t lint test build
